export default [
  'android',
  'java',
  'mobile',
  'android studio',
  'apache spark',
  'hadoop',
  'bigdata',
  'data analysis',
  'sql',
  'data science',
  'continuous integration',
  'api',
  'hl7 fhir',
  'json',
  'react native',
  'ruby on rails',
  'c',
  'c++',
  'docker',
  'gstreamer',
  'computer vision',
  'javascript',
  'node.js',
  'typescript',
  'mongodb',
  'amazon web services',
  'shell',
  'linux',
  'unix',
  'sysadmin',
  'css',
  'html5',
  'angular',
  '.net',
  'c#',
  'azure',
  'asp.net web api',
  'terraform',
  'security',
  'automation',
  'devops',
  'sre',
  'python',
  'ruby',
  'apache',
  'machine learning',
  'algorithm',
  'statistics',
  'business intelligence',
  'rest',
  'web services',
  'php',
  'laravel',
  'reactjs',
  'asp.net',
  'flask',
  'database performance',
  'azure devops',
  'visual studio',
  'rust',
  'agile',
  'angularjs',
  'git',
  'redux',
  'cypress',
  'architecture',
  'database design',
  'ansible',
  'sdn',
  'gsuite',
  'go',
  'django',
  'matillion',
  'isml',
  'controllers',
  'demandware',
  'salesforce communities',
  'salesforce commerce cloud',
  'kubernetes',
  'webassembly',
  'graphics',
  'rendering',
  'webgl',
  'microservices',
  'mesos',
  'marathon',
  'mobx',
  'ffmpeg',
  'tsql',
  'sql server',
  'oop',
  'ibm sterling',
  'sterling db',
  'oracle',
  'middleware',
  'postgresql',
  'spring',
  'postgis',
  'html',
  'jenkins',
  'powershell',
  'bash',
  'design',
  'blockchain',
  'graphql',
  'xamarin',
  'autodesk navisworks',
  'github',
  'spring boot',
  'vue.js',
  'd3.js',
  'networking',
  'kotlin',
  'less',
  'sass',
  'scala',
  'playframework',
  'saas',
  'google cloud platform',
  'backend',
  'robotics',
  'ros',
  'bim',
  'salesforce',
  'implementation',
  'react',
  'mysql',
  'nginx',
  'aws',
  'haskell',
  'project management',
  'zend framework',
  'splunk',
  'p2p',
  'ios',
  'snapchat',
  'objective c',
  'swift',
  'symfony',
  'typo3',
  'extbase',
  'wordpress',
  'react native android',
  'continuous deployment',
  'cloud',
  'jira',
  'erp',
  'crm',
  'metal',
  'opengl',
  'virtual reality',
  'airflow',
  'amazon redshift',
  'etl',
  'jquery',
  'network programming',
  'dns',
  'service level agreement',
  'cluster computing',
  'openshift',
  'express',
  'ionic framework',
  'websocket',
  'pug',
  'knockout.js',
  'php 7',
  'user interface',
  'user experience',
  'hibernate',
  'apache kafka',
  'css3',
  'magento2',
  'ajax',
  'cakephp',
  'elasticsearch',
  'ubuntu',
  'lxc',
  'zfs',
  'elk',
  'database',
  'erlang',
  'influxdb',
  'embedded',
  'cryptography',
  'xml',
  'asp.net core',
  'gitlab',
  'logstash',
  'symfony2',
  'web applications',
  'qa',
  'testing',
  'web',
  'python 2to3',
  'gunicorn',
  'data structures',
  'parallel processing',
  'amazon s3',
  'posix',
  'tableau',
  'data visualization',
  'visualization',
  'asp.net mvc',
  'zendesk',
  'golang',
  'redis',
  'lit element',
  'web component',
  'webpack',
  'rabbitmq',
  'gin gonic',
  'balsamiq',
  'spring data jpa',
  'reactnative',
  'pytest',
  'algolia',
  'firebase',
  'java 8',
  'rpg',
  'enterprise architect',
  'software design',
  'software distribution',
  'javafx',
  'swing',
  'swingx',
  'woocommerce',
  'sketchapp',
  'twitter bootstrap',
  'soa',
  'selenium',
  'amazon elastic beanstalk',
  'apollo',
  'graph',
  'nosql',
  'discord',
  'ember.js',
  'shopify',
  'distributed computing',
  'multithreading',
  'concurrency',
  'distributed system',
  'performance testing',
  'next.js',
  'enterprise',
  'secure coding',
  'kafka',
  'xcode',
  'macos',
  'heroku',
  'gwt',
  'gwtp',
  'office365',
  'azure active directory',
  'react redux',
  'financial',
  'jhipster',
  'tensorflow',
  'keras',
  'pytorch',
  'sklearn pandas',
  'numpy',
  'kubebuilder',
  'containers',
  'sqlalchemy',
  'java ee',
  'ionic2',
  'three.js',
  '3d',
  'mvvm',
  'leaflet',
  'google maps',
  'geolocation',
  'react bootstrap',
  'episerver',
  'umbraco',
  'sitecore',
  'dotnetnuke',
  'orchardcms',
  'chef',
  'dsc',
  'sdk',
  'babel',
  'spinnaker',
  'excel',
  'math',
  'quantitative finance',
  'finance',
  'html5 canvas',
  'seo',
  'scikit learn',
  'varnish',
  'apache flink',
  'single page application',
  'windows services',
  'wpf',
  'grpc',
  'com',
  'wcf',
  'blazor',
  'api design',
  'hashicorp vault',
  'tdd',
  'liquid',
  'admin',
  'user management',
  'device manager',
  'ou',
  'activemq',
  'frontend',
  'cherrypy',
  'hbase',
  'unity3d',
  'game engine',
  'cocos2d iphone',
  'libgdx',
  'unity5',
  'geospatial',
  'saml',
  'oauth',
  'openid connect',
  'fast ai',
  'pipeline',
  'flutter',
  'dart',
  'debugging',
  'webrtc',
  'kurento',
  'google analytics',
  'instagram',
  'facebook',
  'back',
  'rest assured',
  'testng',
  'java native interface',
  'spring security',
  'pyramid',
  'web frontend',
  'writing',
  'video',
  'product management',
  'kentico',
  'cms',
  'mvc',
  'hybris',
  'progressive web apps',
  'caching',
  'pulumi',
  'configuration management',
  'telephony',
  'sip',
  'elixir',
  'phoenix',
  'artificial intelligence',
  'magento',
  'socialengine',
  'nightwatch.js',
  'storybook',
  '.net core',
  'hangfire',
  'sequel',
  'cuba',
  'sinatra',
  'amazon kinesis',
  'lamp',
  'p5.js',
  'tcp',
  'ecmascript 6',
  'ecmascript 2017',
  'owasp',
  'grafana',
  'cython',
  'gruntjs',
  'rubyonrails',
  'angular8',
  'centos',
  'rhel',
  'infrastructure',
  'grape',
  'rspec',
  'truffle',
  'jvm',
  'graalvm',
  'electron',
  'jboss',
  'content management system',
  'tomcat',
  'web scraping',
  'kubernetes helm',
  'nodejs',
  'multi threaded',
  'npm',
  'core data',
  'autolayout',
  'uistoryboard',
  'core graphics',
  'akka',
  'typoscript',
  'fluid',
  'bitcoin',
  'ethereum',
  'erc20',
  'communication',
  'product',
  'sfdc',
  'apex',
  'infrastructure as code',
  'linux kernel',
  'encryption',
  'rx java',
  'togaf',
  'automated tests',
  'integration testing',
  'appian',
  'sap',
  'lifecycle'
]
